apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-backend
  namespace: acme-backend
  labels:
    app: acme-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: acme-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
        labels:
          app: acme-backend
    spec:
      containers:
        - name: acme-backend
          image: acme/acme-backend:1.0.2
          imagePullPolicy: Always 
          command:
            - /bin/bash
          args:
            - -c
            - ./acme-server
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
